export const quotes = [
"Quando a vida parecer difícil lembre-se que tudo pode piorar.",
"Agora e daqui pra frente, é só ladeira abaixo.",
"Não desanime, as piores coisas da vida ainda estão chegando por aí!",
"Vencedores nunca param de se vangloriar por suas vitórias. Como sei? Eu vejo, nunca ganhei.",
"Nunca tente piorar o que já está ruim. Deixe que a vida se encarrega de fazer isso pra você.",
"Nunca é tarde demais para errar mais uma vez.",
"Não se preocupe se você perder, nós não esperávamos mais de você!",
"Pare de reclamar de tudo e comece a aceitar que tudo deu errado pra você!",
"Procrastinar é sempre a melhor escolha para você se sentir um completo imbecil.",
"O caminho para o sucesso não está no seu mapa da vida. Aceite!",
"A vida é realmente muito mais difícil para quem é um completo idiota.",
"Pare de tratar como lição mais uma das suas falhas.",
"Mais um dia que se inicia e novas oportunidades para errar surgem com esse novo amanhecer!",
"Há sempre um espaço inútil para não ser aproveitado na vida de quem não tem o que fazer.",
"Pare e pense: todas as suas falhas tem o mesmo causador em comum: Você!",
"Todo mundo tem um propósito na vida mas nem todo mundo vai encontrá-lo. Faz parte.",
"Pare de achar que ninguém gosta de você. Comece a ter certeza disso.",
"A esperança é o sentimento mais nocivo que existe, porque te mantém sofrendo por algo que você nunca vai conseguir.",
"Se você quiser; se você se esforçar; se você treinar; se você entrar de cabeça; se você se concentrar: nada garante que você vai conseguir.",
"Mil cairão a sua direita, 10 mil a sua esquerda. Mas você já estará caído.",
"Conheça o fracassado que há em você e entenda que todos os obstáculos na verdade te ajudam na sua desistência.",
"A mãe da frustração é você acreditar que pode realizar seus sonhos sem ser herdeiro. ",
"Abandone antes de tentar e evite maiores frustrações.Pode ser que seu propósito na vida seja nunca vencer, apenas viver de tentativa.",
"Os que não param de lutar estão sempre em busca da sua próxima derrota. ",
"As piores coisas da sua vida podem acontecer se você decidir sair de onde está.",
"Você não é especial e os outros também não são. Somos todos pessoas normais em busca do fracasso.",
"Todos esperam que você falhe. Então, lute até provar que eles estão certos.",
"Acredite quando falarem que não vai dar certo porque as pessoas são mais inteligentes que você.",
"O caminho não fica mais difícil, você é que fica mais cansado e não aguenta mais.",
"Não é falta de sorte, é incompetência.",
"Se você mudar de ângulo, vai perceber que não o outro lado também não é bom.",
"Não pense porque já deu tudo errado que as coisas não podem sair ainda mais do controle.",
"O gosto da vitória é momentâneo, o do fracasso dura para sempre.",
"Não desanime, a derrota de hoje nem se compara com a de amanhã.",
"Você é mais fraco do que pensa.",
"Lute como nunca, perca como sempre.",
"O não você já tem, agora falta buscar a humilhação.",
"Seja o protagonista do seu fracasso.",
"Uma grande jornada termina com uma bela derrota.",
"Tudo pode acontecer, inclusive nada.",
"Tudo passa, nem que seja por cima de você.",
"Não pare, faça até dar errado.",
"Nunca é tarde demais pra parar de sonhar.",
"Existem poucos prazeres maiores do que desistir.",
"Coincidências existem e normalmente estão contra você.",
"O primeiro passo para a derrota é começar.",
"Errar, Superar, Aprender e Desistir.",
"Só existe uma coisa que te separa dos seus objetivos, sua capacidade.",
"Ninguém precisa de humilhar. Um espelho já faz isso.",
"Muitos vão dizer que você não vai conseguir. Acredite neles.",
"Nenhum obstáculo é grande para quem desiste.",
"A maior derrota é acreditar que você é capaz.",
"Pare de desejar e comece a desistir.",
"A vida te derruba hoje preparando para a queda de amanhã.",
"Você é mais fraco do que pensa.",
"Não espere um motivo para desistir, seja o motivo.",
"Acredite, você nasceu para conquistar grandes fracassos.",
"Desistir é uma nova chance de recomeçar.",
"Quando tudo estiver dando errado, se acostume.",
"Você não falha quando erra, falha quando tenta.",
"É preciso fechar ciclos, para fracassar em algo novo.",
"Nunca espere nada de ninguém, muito menos de você.",
"Fracassar não é o fim. Recomece e fracasse até desistir.",
"Não pare até se humilhar.",
"Coisas ruins se vão, para que piores possam vir.",
"Nada como um dia pior que o outro.",
"A vida não é uma caixinha de surpresas, é um container de decepções.",
"Não é porque algo deu errado até agora que vai dar certo daqui pra frente.",
"A cada passo pra frente, três passos para trás.",
"Melhor sorrir de desespero do que chorar de alegria.",
"Não desista nas primeiras tentativas, desista antes mesmo de tentar.",


]