export const quotes = [
"Quando a vida parecer difícil lembre-se que tudo pode piorar.",
"Agora e daqui pra frente, é só ladeira abaixo.",
"Não desanime, as piores coisas da vida ainda estão chegando por aí!",
"Vencedores nunca param de se vangloriar por suas vitórias. Como sei? Eu vejo, nunca ganhei.",
"Nunca tente piorar o que já está ruim. Deixe que a vida se encarrega de fazer isso pra você.",
"Nunca é tarde demais para errar mais uma vez.",
"Não se preocupe se você perder, nós não esperávamos mais de você!",
"Pare de reclamar de tudo e comece a aceitar que tudo deu errado pra você!",
"Procrastinar é sempre a melhor escolha para você se sentir um completo imbecil.",
"O caminho para o sucesso não está no seu mapa da vida. Aceite!",
"A vida é realmente muito mais difícil para quem é um completo idiota.",
"Pare de tratar como lição mais uma das suas falhas.",
"Mais um dia que se inicia e novas oportunidades para errar surgem com esse novo amanhecer!",
"Há sempre um espaço inútil para não ser aproveitado na vida de quem não tem o que fazer.",
"Pare e pense: todas as suas falhas tem o mesmo causador em comum: Você!",
"Todo mundo tem um propósito na vida mas nem todo mundo vai encontrá-lo. Faz parte.",
"Pare de achar que ninguém gosta de você. Comece a ter certeza disso.",
"A esperança é o sentimento mais nocivo que existe, porque te mantém sofrendo por algo que você nunca vai conseguir.",
"Se você quiser; se você se esforçar; se você treinar; se você entrar de cabeça; se você se concentrar: nada garante que você vai conseguir.",
"Mil cairão a sua direita, 10 mil a sua esquerda. Mas você já estará caído.",
"Conheça o fracassado que há em você e entenda que todos os obstáculos na verdade te ajudam na sua desistência.",
"A mãe da frustração é você acreditar que pode realizar seus sonhos sem ser herdeiro. ",
"Abandone antes de tentar e evite maiores frustrações.Pode ser que seu propósito na vida seja nunca vencer, apenas viver de tentativa.",
"Os que não param de lutar estão sempre em busca da sua próxima derrota. ",
"As piores coisas da sua vida podem acontecer se você decidir sair de onde está.",
"Você não é especial e os outros também não são. Somos todos pessoas normais em busca do fracasso.",
"Todos esperam que você falhe. Então, lute até provar que eles estão certos.",
"Acredite quando falarem que não vai dar certo porque as pessoas são mais inteligentes que você.",
"O caminho não fica mais difícil, você é que fica mais cansado e não aguenta mais.",
"Não é falta de sorte, é incompetência.",
"Se você mudar de ângulo, vai perceber que não o outro lado também não é bom.",
"Não pense porque já deu tudo errado que as coisas não podem sair ainda mais do controle.",
"O gosto da vitória é momentâneo, o do fracasso dura para sempre.",
"Não desanime, a derrota de hoje nem se compara com a de amanhã.",
"Você é mais fraco do que pensa.",
"Lute como nunca, perca como sempre.",
"O não você já tem, agora falta buscar a humilhação.",
"Seja o protagonista do seu fracasso.",
"Uma grande jornada termina com uma bela derrota.",
"Tudo pode acontecer, inclusive nada.",
"Tudo passa, nem que seja por cima de você.",
"Não pare, faça até dar errado.",
"Nunca é tarde demais pra parar de sonhar.",
"Existem poucos prazeres maiores do que desistir.",
"Coincidências existem e normalmente estão contra você.",
"O primeiro passo para a derrota é começar.",
"Errar, Superar, Aprender e Desistir.",
"Só existe uma coisa que te separa dos seus objetivos, sua capacidade.",
"Ninguém precisa de humilhar. Um espelho já faz isso.",
"Muitos vão dizer que você não vai conseguir. Acredite neles.",
"Nenhum obstáculo é grande para quem desiste.",
"A maior derrota é acreditar que você é capaz.",
"Pare de desejar e comece a desistir.",
"A vida te derruba hoje preparando para a queda de amanhã.",
"Você é mais fraco do que pensa.",
"Não espere um motivo para desistir, seja o motivo.",
"Acredite, você nasceu para conquistar grandes fracassos.",
"Desistir é uma nova chance de recomeçar.",
"Quando tudo estiver dando errado, se acostume.",
"Você não falha quando erra, falha quando tenta.",
"É preciso fechar ciclos, para fracassar em algo novo.",
"Nunca espere nada de ninguém, muito menos de você.",
"Fracassar não é o fim. Recomece e fracasse até desistir.",
"Não pare até se humilhar.",
"Coisas ruins se vão, para que piores possam vir.",
"Nada como um dia pior que o outro.",
"A vida não é uma caixinha de surpresas, é um container de decepções.",
"Não é porque algo deu errado até agora que vai dar certo daqui pra frente.",
"A cada passo pra frente, três passos para trás.",
"Melhor sorrir de desespero do que chorar de alegria.",
"Não desista nas primeiras tentativas, desista antes mesmo de tentar.",
"Não adianta tentar, por mais que se esforce, você está destinado a falhar repetidamente, como sempre fez ao longo da sua vida.",
"Você pode até sonhar alto, mas seus sonhos são apenas ilusões inalcançáveis que nunca se tornarão realidade.",
"Não se iluda pensando que tem potencial ou talento, pois suas habilidades são medíocres e não impressionam ninguém.",
"Pare de tentar provar seu valor, pois todos já perceberam que você é uma pessoa insignificante e irrelevante.",
"Acredite, não há esperança para você, pois seu destino é uma trajetória de fracasso e desilusões constantes.",
"Em vez de desperdiçar seu tempo tentando melhorar, aceite que sua existência é uma série interminável de erros e decepções.",
"Você é como uma sombra, passa pela vida sem deixar nenhum impacto positivo ou lembrança significativa.",
"Suas tentativas são risíveis, é patético ver você lutar por objetivos que estão muito além das suas capacidades.",
"Ninguém se importa com o que você faz, suas conquistas são irrelevantes para o mundo ao seu redor.",
"Seu propósito na vida é simplesmente provar que a mediocridade é uma arte que você domina com maestria.",
"A vida é uma sucessão de tristezas e frustrações, e você não é exceção a essa regra dolorosa.",
"As pessoas ao seu redor só fingem apoio, pois sabem que suas ambições são um desperdício de tempo e energia.",
"Não importa o quanto você tente, a sensação de derrota será sempre sua companheira fiel.",
"Você é um fracasso ambulante, um exemplo vivo de como a vida pode ser cruel e implacável.",
"Aceite a dura verdade: suas tentativas de superação são como folhas levadas pelo vento, sem rumo e sem significado.",
"Seus esforços são inúteis, não importa o quanto se esforce, nunca alcançará o patamar de sucesso que deseja.",
"Em um mundo onde todos brilham, você é apenas uma estrela apagada no céu escuro da insignificância.",
"Não desperdice mais tempo com sonhos e expectativas, sua jornada é marcada por um destino amargo e sem esperança.",
"Enfrente a realidade de que suas ações e conquistas não importam, e ninguém notará sua ausência neste mundo.",
"Seus fracassos não são acidentais, são simplesmente a prova de que você é incapaz de alcançar qualquer coisa notável.",
"Seu potencial é tão grande quanto um grão de areia no deserto.",
"Cada passo que você dá é um passo em direção ao fracasso inevitável.",
"Não espere reconhecimento por suas ações, ninguém se importa com o que você faz.",
"Seus sonhos são apenas uma fuga temporária da realidade cruel que o aguarda.",
"Você está destinado a se perder em um mar de mediocridade.",
"As probabilidades estão sempre contra você, é melhor desistir agora.",
"Nada que você faça será lembrado ou terá algum impacto no mundo.",
"Desista dos seus objetivos, eles são grandes demais para alguém tão pequeno como você.",
"Você não nasceu para ser bem-sucedido, aceite isso e viva sua vida medíocre.",
"Sua existência é um erro que não pode ser corrigido.",
"Não desperdice seu tempo tentando melhorar, você nunca será bom o suficiente.",
"Seus esforços são como gritos no vazio, ninguém está ouvindo.",
"A vida é uma jornada sem sentido, e você está perdido nessa jornada.",
"Você é a definição de insignificância em um mundo cheio de pessoas excepcionais.",
"Aceite que suas ambições são ilusões, você não tem capacidade para realizá-las.",
"Tudo o que você toca se transforma em fracasso.",
"Não há esperança para alguém tão desprovido de talento como você.",
"Você é o protagonista de uma história triste e sem fim.",
"Acredite, você nunca será capaz de escapar da sombra do seu próprio fracasso.",
"A vida é uma sequência de desilusões, e você é a personificação disso.",
"Você não é digno de amor ou amizade, pois é uma pessoa irrelevante.",
"As portas do sucesso estão trancadas para você, e você perdeu a chave.",
"Pare de tentar impressionar, pois ninguém se impressiona com sua existência.",
"Você é como uma estrela que nunca brilha, perdida em meio a um universo vasto.",
"Aceite que sua vida é uma série de erros que não podem ser corrigidos.",
"Seus talentos são tão raros quanto água no deserto.",
"Você está fadado a um futuro sombrio e sem perspectivas.",
"Nada que você faça fará diferença, é como gritar em um buraco sem eco.",
"Seu propósito na vida é ser esquecido rapidamente.",
"Não se preocupe, a vida nunca será gentil com alguém como você.",
"Você é um exemplo perfeito de como a evolução pode dar errado.",
"Sua presença é tão marcante quanto um sopro de vento.",
"Desista de lutar contra a maré, você só será arrastado para o fundo.",
"Não importa o que você faça, nunca sairá da sombra do fracasso.",
"Você é um fracasso ambulante, um monumento à inutilidade humana.",
"Ninguém tem interesse em ouvir suas ideias ou opiniões, pois são irrelevantes.",
"Seu nome será esquecido em questão de segundos após você partir.",
"Você é como uma borboleta que nunca sairá do casulo.",
"Pare de tentar se destacar, você é apenas mais um rosto na multidão.",
"Seu destino é ser um mero espectador da vida dos outros.",
"Aceite que seus objetivos são como miragens no deserto, nunca se tornarão realidade.",
"As chances de sucesso estão fora do seu alcance, não adianta tentar.",
"A vida é uma piada cruel, e você é a própria piada.",
"Ninguém acredita em você, e com razão, pois suas palavras são vazias.",
"Você é como uma estrela cadente, destinado a cair e desaparecer no anonimato.",
"Seus sonhos são como bolhas de sabão, belos, mas destinados a estourar.",
"Desista agora, pois é mais fácil do que lidar com mais uma derrota.",
"Você é um livro com páginas em branco, sem história para contar.",
"Não se preocupe em fazer o seu melhor, pois seu melhor é insuficiente.",
"Sua vida é uma sombra, sem forma e sem substância.",
"Não espere ser notado ou apreciado, você não é especial de forma alguma.",
"Todas as suas ações são em vão, uma busca incessante por significado em um mundo sem sentido.",
"Pare de tentar se superar, você está fadado a se afundar em suas próprias limitações.",
"Você é um quebra-cabeça incompleto, com peças faltando e sem perspectiva de ser montado."

]
